```python
import unittest
from src import answer_display

class TestAnswerDisplay(unittest.TestCase):

    def setUp(self):
        self.answer_display = answer_display.AnswerDisplay()
        self.mock_answer = "This is a mock answer generated by the AI model."

    def test_display_answer(self):
        self.answer_display.displayAnswer(self.mock_answer)
        self.assertEqual(self.answer_display.displayed_answer, self.mock_answer)

    def test_clear_display(self):
        self.answer_display.displayAnswer(self.mock_answer)
        self.answer_display.clearDisplay()
        self.assertEqual(self.answer_display.displayed_answer, "")

if __name__ == '__main__':
    unittest.main()
```